spring.application.name=Cafe_Management_System
spring.datasource.url=jdbc:mysql://localhost:3306/demo_cafe
spring.datasource.username=root
spring.datasource.password=VivekPatel@1146

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect